#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL="$ROOT/.local"
BIN="$LOCAL/bin"
AGBCC_SRC="$LOCAL/src/agbcc"
AGBCC_PREFIX="$LOCAL/agbcc-sdk"
MGBA_DIR="$LOCAL/emulators/mgba"
MGBA_VERSION="${MGBA_VERSION:-0.10.5}"
AGBCC_COMMIT="${AGBCC_COMMIT:-da598c1d918402c42c0c0d7128ba14567f3175e9}"

mkdir -p "$BIN" "$LOCAL/src" "$MGBA_DIR" "$AGBCC_PREFIX"

as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        echo "error: root privileges are required for: $*" >&2
        exit 1
    fi
}

install_host_packages() {
    if command -v apt-get >/dev/null 2>&1; then
        as_root apt-get update
        as_root apt-get install -y \
            ca-certificates curl wget git make gcc g++ python3 python3-pip \
            pkg-config libpng-dev xz-utils unzip file jq
    elif command -v brew >/dev/null 2>&1; then
        brew install git make gcc libpng pkg-config wget jq
    elif command -v pacman >/dev/null 2>&1; then
        as_root pacman -Syu --needed --noconfirm \
            base-devel git python libpng pkgconf wget curl xz unzip file jq
    else
        echo "error: unsupported host package manager; install Git, GNU Make, GCC/G++, Python 3, pkg-config and libpng manually" >&2
        exit 1
    fi
}

install_devkitarm() {
    if [ -f /etc/profile.d/devkit-env.sh ]; then
        # shellcheck disable=SC1091
        source /etc/profile.d/devkit-env.sh
    fi
    if [ -n "${DEVKITARM:-}" ] && [ -x "$DEVKITARM/bin/arm-none-eabi-as" ]; then
        return
    fi
    if command -v arm-none-eabi-as >/dev/null 2>&1; then
        return
    fi

    if command -v dkp-pacman >/dev/null 2>&1; then
        as_root dkp-pacman -Sy --noconfirm
        as_root dkp-pacman -S --needed --noconfirm gba-dev
    elif command -v apt-get >/dev/null 2>&1; then
        tmp="$(mktemp -d)"
        trap 'rm -rf "$tmp"' RETURN
        curl -fsSL https://apt.devkitpro.org/install-devkitpro-pacman -o "$tmp/install-devkitpro-pacman"
        chmod +x "$tmp/install-devkitpro-pacman"
        as_root "$tmp/install-devkitpro-pacman"
        as_root dkp-pacman -Sy --noconfirm
        as_root dkp-pacman -S --needed --noconfirm gba-dev
        trap - RETURN
        rm -rf "$tmp"
    else
        echo "error: devkitARM/gba-dev is not installed; see https://devkitpro.org/wiki/devkitPro_pacman" >&2
        exit 1
    fi

    if [ -f /etc/profile.d/devkit-env.sh ]; then
        # shellcheck disable=SC1091
        source /etc/profile.d/devkit-env.sh
    fi
    export DEVKITPRO="${DEVKITPRO:-/opt/devkitpro}"
    export DEVKITARM="${DEVKITARM:-$DEVKITPRO/devkitARM}"
}

install_agbcc() {
    if [ ! -d "$AGBCC_SRC/.git" ]; then
        git clone https://github.com/pret/agbcc.git "$AGBCC_SRC"
    fi
    git -C "$AGBCC_SRC" fetch --all --tags --prune
    git -C "$AGBCC_SRC" checkout --detach "$AGBCC_COMMIT"
    (
        cd "$AGBCC_SRC"
        ./build.sh
        ./install.sh "$AGBCC_PREFIX"
    )
}

install_mgba() {
    case "$(uname -m)" in
        x86_64|amd64) asset_arch="x64" ;;
        aarch64|arm64) asset_arch="arm64" ;;
        *) echo "error: unsupported mGBA AppImage architecture: $(uname -m)" >&2; exit 1 ;;
    esac

    image="$MGBA_DIR/mGBA-${MGBA_VERSION}.AppImage"
    url="https://github.com/mgba-emu/mgba/releases/download/${MGBA_VERSION}/mGBA-${MGBA_VERSION}-appimage-${asset_arch}.appimage"
    if [ ! -s "$image" ]; then
        curl -fL --retry 3 --retry-delay 2 "$url" -o "$image"
        chmod +x "$image"
    fi
    ln -sfn "$image" "$BIN/mgba"
}

write_env() {
    cat > "$LOCAL/env.sh" <<ENV
# Generated by tools/setup_gba_environment.sh
export DEVKITPRO="${DEVKITPRO:-/opt/devkitpro}"
export DEVKITARM="${DEVKITARM:-${DEVKITPRO:-/opt/devkitpro}/devkitARM}"
export AGBCC_ROOT="$AGBCC_PREFIX/tools/agbcc"
export MGBA_HOME="$MGBA_DIR"
export PATH="$BIN:${DEVKITARM:-${DEVKITPRO:-/opt/devkitpro}/devkitARM}/bin:\$PATH"
ENV
}

check_environment() {
    if [ -f "$LOCAL/env.sh" ]; then
        # shellcheck disable=SC1090
        source "$LOCAL/env.sh"
    fi
    python3 "$ROOT/tools/check_gba_environment.py"
}

case "${1:-install}" in
    install)
        install_host_packages
        install_devkitarm
        install_agbcc
        install_mgba
        write_env
        check_environment
        ;;
    check)
        check_environment
        ;;
    *)
        echo "usage: $0 [install|check]" >&2
        exit 2
        ;;
esac
